// ---------------------------------------------------------------------
// DASHBOARD DATA — SINGLE SOURCE OF TRUTH
//
// To move a component along, change its `status` (one of the STATUS keys
// defined in index.html: "not-started" | "bazel-make" | "bazel-only") and
// fill in pr / contributor / company / notes as they become known.
// ---------------------------------------------------------------------

const STATUS = {
  "not-started": { label: "Not Started", cls: "not-started", logos: [] },
  "bazel-make": { label: "Bazel+Make", cls: "bazel-make", logos: [] },
  "bazel-only": { label: "Bazel-only", cls: "bazel-only", logos: ["bazel"] },
};

// Render order for the table: most-progressed first.
const STATUS_ORDER = ["bazel-only", "bazel-make", "not-started"];

// Build-system logo files (local, in assets/).
const BUILD_LOGOS = {
  bazel: { src: "assets/bazel.svg", alt: "Bazel" },
  make: { src: "assets/make.svg", alt: "Make" },
};

const PR_BASE = "https://github.com/sonic-net/sonic-buildimage/pull/";

// PR number -> its state on GitHub. Update this as PRs move along.
const PR_STATUSES = {
  28005: "draft",
};

// PR state -> icon + label. Icons are Octicons (MIT) in assets/, pre-coloured
// per state. A PR with no entry in PR_STATUSES renders as a link with no icon.
const PR_STATUS_ICONS = {
  draft: { label: "Draft", icon: "assets/pr-draft.svg" },
  open: { label: "Open", icon: "assets/pr-open.svg" },
  merged: { label: "Merged", icon: "assets/pr-merged.svg" },
  closed: { label: "Closed", icon: "assets/pr-closed.svg" },
};

// Contributors are GitHub handles; this prefixes their profile URL.
const GITHUB_BASE = "https://github.com/";

// Fixed company roster, keyed by slug.
// Companies without an entry fall back to showing their raw `company` slug as text in the table.
// `url` is optional: with it the logo links to the company homepage, without it it renders plain.
const COMPANIES = {
  "aspect": { name: "Aspect Build", logo: "assets/aspect.png", url: "https://aspect.build" },
};

// The SONiC Components we care about, and their migration status.
// Row set: dockers/docker-* dirs + all rules/*.mk components (deduped).
const COMPONENTS = [
  { name: "docker-sysmgr", status: "bazel-make", pr: 28005, contributor: "blorente", company: "aspect" },
  { name: "libnl3", status: "bazel-make", pr: 28005, contributor: "blorente", company: "aspect" },
  { name: "sysmgr", status: "bazel-make", pr: 28005, contributor: "blorente", company: "aspect" },
  { name: "swss-common", status: "bazel-make", pr: 28005, contributor: "blorente", company: "aspect" },
  { name: "asyncsnmp-py3", status: "not-started" },
  { name: "bash", status: "not-started" },
  { name: "dash-ha", status: "not-started" },
  { name: "dash-sai", status: "not-started" },
  { name: "dbsyncd-py3", status: "not-started" },
  { name: "dhcp4relay", status: "not-started" },
  { name: "dhcpmon", status: "not-started" },
  { name: "dhcprelay", status: "not-started" },
  { name: "docker-base", status: "not-started" },
  { name: "docker-base-bookworm", status: "not-started" },
  { name: "docker-base-bullseye", status: "not-started" },
  { name: "docker-base-buster", status: "not-started" },
  { name: "docker-base-stretch", status: "not-started" },
  { name: "docker-base-trixie", status: "not-started" },
  { name: "docker-basic_router", status: "not-started" },
  { name: "docker-bmp", status: "not-started" },
  { name: "docker-bmp-watchdog", status: "not-started" },
  { name: "docker-config-engine", status: "not-started" },
  { name: "docker-config-engine-bookworm", status: "not-started" },
  { name: "docker-config-engine-bullseye", status: "not-started" },
  { name: "docker-config-engine-buster", status: "not-started" },
  { name: "docker-config-engine-stretch", status: "not-started" },
  { name: "docker-config-engine-trixie", status: "not-started" },
  { name: "docker-dash-ha", status: "not-started" },
  { name: "docker-database", status: "not-started" },
  { name: "docker-dhcp-relay", status: "not-started" },
  { name: "docker-dhcp-server", status: "not-started" },
  { name: "docker-eventd", status: "not-started" },
  { name: "docker-fpm", status: "not-started" },
  { name: "docker-fpm-frr", status: "not-started" },
  { name: "docker-fpm-gobgp", status: "not-started" },
  { name: "docker-gnmi", status: "not-started" },
  { name: "docker-gnmi-sidecar", status: "not-started" },
  { name: "docker-gnmi-watchdog", status: "not-started" },
  { name: "docker-iccpd", status: "not-started" },
  { name: "docker-lldp", status: "not-started" },
  { name: "docker-macsec", status: "not-started" },
  { name: "docker-mux", status: "not-started" },
  { name: "docker-nat", status: "not-started" },
  { name: "docker-orchagent", status: "not-started" },
  { name: "docker-otel", status: "not-started" },
  { name: "docker-p4rt", status: "not-started" },
  { name: "docker-pde", status: "not-started" },
  { name: "docker-platform-monitor", status: "not-started" },
  { name: "docker-ptf", status: "not-started" },
  { name: "docker-ptf-sai", status: "not-started" },
  { name: "docker-restapi", status: "not-started" },
  { name: "docker-restapi-sidecar", status: "not-started" },
  { name: "docker-restapi-watchdog", status: "not-started" },
  { name: "docker-router-advertiser", status: "not-started" },
  { name: "docker-sflow", status: "not-started" },
  { name: "docker-snmp", status: "not-started" },
  { name: "docker-sonic-bmp", status: "not-started" },
  { name: "docker-sonic-gnmi", status: "not-started" },
  { name: "docker-sonic-mgmt", status: "not-started" },
  { name: "docker-sonic-mgmt-framework", status: "not-started" },
  { name: "docker-sonic-otel", status: "not-started" },
  { name: "docker-sonic-p4rt", status: "not-started" },
  { name: "docker-sonic-redfish", status: "not-started" },
  { name: "docker-sonic-restapi", status: "not-started" },
  { name: "docker-sonic-sdk", status: "not-started" },
  { name: "docker-sonic-sdk-buildenv", status: "not-started" },
  { name: "docker-sonic-telemetry", status: "not-started" },
  { name: "docker-stp", status: "not-started" },
  { name: "docker-swss-layer-bookworm", status: "not-started" },
  { name: "docker-swss-layer-bullseye", status: "not-started" },
  { name: "docker-swss-layer-buster", status: "not-started" },
  { name: "docker-swss-layer-trixie", status: "not-started" },
  { name: "docker-teamd", status: "not-started" },
  { name: "docker-telemetry", status: "not-started" },
  { name: "docker-telemetry-sidecar", status: "not-started" },
  { name: "docker-telemetry-watchdog", status: "not-started" },
  { name: "eventd", status: "not-started" },
  { name: "flashrom", status: "not-started" },
  { name: "frr", status: "not-started" },
  { name: "gobgp", status: "not-started" },
  { name: "grpc", status: "not-started" },
  { name: "grub2", status: "not-started" },
  { name: "iccpd", status: "not-started" },
  { name: "ifupdown2", status: "not-started" },
  { name: "initramfs-tools", status: "not-started" },
  { name: "iproute2", status: "not-started" },
  { name: "iptables", status: "not-started" },
  { name: "isc-dhcp", status: "not-started" },
  { name: "ixgbe", status: "not-started" },
  { name: "kdump-tools", status: "not-started" },
  { name: "libteam", status: "not-started" },
  { name: "libyang3", status: "not-started" },
  { name: "libyang3-py3", status: "not-started" },
  { name: "linkmgrd", status: "not-started" },
  { name: "linux-kernel", status: "not-started" },
  { name: "lldpd", status: "not-started" },
  { name: "lm-sensors", status: "not-started" },
  { name: "makedumpfile", status: "not-started" },
  { name: "monit", status: "not-started" },
  { name: "mpdecimal", status: "not-started" },
  { name: "openssh", status: "not-started" },
  { name: "p4lang", status: "not-started" },
  { name: "p4rt", status: "not-started" },
  { name: "phy-credo", status: "not-started" },
  { name: "protobuf", status: "not-started" },
  { name: "ptf", status: "not-started" },
  { name: "ptf-py3", status: "not-started" },
  { name: "radius", status: "not-started" },
  { name: "rasdaemon", status: "not-started" },
  { name: "rdb-cli", status: "not-started" },
  { name: "redis", status: "not-started" },
  { name: "redis-dump-load-py2", status: "not-started" },
  { name: "redis-dump-load-py3", status: "not-started" },
  { name: "restapi", status: "not-started" },
  { name: "sairedis", status: "not-started" },
  { name: "scapy", status: "not-started" },
  { name: "sedutil", status: "not-started" },
  { name: "sflow", status: "not-started" },
  { name: "snmpd", status: "not-started" },
  { name: "socat", status: "not-started" },
  { name: "sonic_bgpcfgd", status: "not-started" },
  { name: "sonic_bmpcfgd", status: "not-started" },
  { name: "sonic-bmcctld", status: "not-started" },
  { name: "sonic-bmp", status: "not-started" },
  { name: "sonic-chassisd", status: "not-started" },
  { name: "sonic-config", status: "not-started" },
  { name: "sonic-containercfgd", status: "not-started" },
  { name: "sonic-ctrmgrd", status: "not-started" },
  { name: "sonic-ctrmgrd-rs", status: "not-started" },
  { name: "sonic-dash-api", status: "not-started" },
  { name: "sonic-device-data", status: "not-started" },
  { name: "sonic-dhcp-utilities", status: "not-started" },
  { name: "sonic-fib", status: "not-started" },
  { name: "sonic-fips", status: "not-started" },
  { name: "sonic-frr-mgmt-framework", status: "not-started" },
  { name: "sonic-genl-packet-ko", status: "not-started" },
  { name: "sonic-genl-packet-tools", status: "not-started" },
  { name: "sonic-host-services", status: "not-started" },
  { name: "sonic-host-services-data", status: "not-started" },
  { name: "sonic-host-services-rs", status: "not-started" },
  { name: "sonic-ledd", status: "not-started" },
  { name: "sonic-libgenl-packet", status: "not-started" },
  { name: "sonic-mgmt-common", status: "not-started" },
  { name: "sonic-mgmt-framework", status: "not-started" },
  { name: "sonic-nettools", status: "not-started" },
  { name: "sonic-pcied", status: "not-started" },
  { name: "sonic-platform-common", status: "not-started" },
  { name: "sonic-psud", status: "not-started" },
  { name: "sonic-py-common", status: "not-started" },
  { name: "sonic-redfish", status: "not-started" },
  { name: "sonic-sensormond", status: "not-started" },
  { name: "sonic-stormond", status: "not-started" },
  { name: "sonic-stp", status: "not-started" },
  { name: "sonic-supervisord-utilities", status: "not-started" },
  { name: "sonic-supervisord-utilities-rs", status: "not-started" },
  { name: "sonic-syseepromd", status: "not-started" },
  { name: "sonic-thermalctld", status: "not-started" },
  { name: "sonic-utilities", status: "not-started" },
  { name: "sonic-utilities-data", status: "not-started" },
  { name: "sonic-xcvrd", status: "not-started" },
  { name: "sonic-yang-mgmt-py3", status: "not-started" },
  { name: "sonic-yang-models-py3", status: "not-started" },
  { name: "sonic-ycabled", status: "not-started" },
  { name: "sonic-ztp", status: "not-started" },
  { name: "supervisor", status: "not-started" },
  { name: "swss", status: "not-started" },
  { name: "swsssdk-py2", status: "not-started" },
  { name: "swsssdk-py3", status: "not-started" },
  { name: "syncd", status: "not-started" },
  { name: "syslog-counter", status: "not-started" },
  { name: "system-health", status: "not-started" },
  { name: "systemd-sonic-generator", status: "not-started" },
  { name: "tacacs", status: "not-started" },
  { name: "telemetry", status: "not-started" },
  { name: "thrift", status: "not-started" },
  { name: "thrift_0_14_1", status: "not-started" },
  { name: "wpasupplicant", status: "not-started" },
];
